version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4009:4009"
    environment:
      NODE_ENV: production
      PORT: 4009
      HOSTNAME: "0.0.0.0"
